<a href="https://colab.research.google.com/github/oguz55han/github/blob/main/Asignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

**``NOTE:``** For installation instructions, please refer to the notebook at SESSION-01 (Numpy Part-01)

In [ ]:
import numpy as np

**REMINDER**<br>
NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays. In numpy dimensions are called as axes.

**Why do we need NumPy?**

A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Concatenation of the Arrays</p>

<a id="00"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this lecture we will first discuss how to concatenate, split and sort the arrays.

**``concatenate((a1, a2, ...), axis=0, out=None)``**

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [ ]:
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((x, y, z))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.concatenate([x, y, z], axis = 1) 

In [ ]:
np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis = 1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [ ]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
v

array([2, 1, 4, 3, 5])

In [ ]:
v.sort()

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="00.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [ ]:
x


array([1, 2, 3])

In [ ]:
y


array([4, 5, 6])

In [ ]:
z

array([7, 8, 9])

In [ ]:
np.concatenate((x,y,z) , axis = 0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate([[x,y,z]] , axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array([x,y,z])


NameError: ignored

2d matrix

In [ ]:
a = np.random.randint(10,size=(2,3))
b= np.random.randint(10,size=(2,3))

In [ ]:
a


array([[6, 5, 8],
       [2, 6, 1]])

In [ ]:
b

array([[9, 9, 6],
       [3, 3, 5]])

In [ ]:
a,b

(array([[6, 5, 8],
        [2, 6, 1]]), array([[9, 9, 6],
        [3, 3, 5]]))

In [ ]:
np.concatenate((a,b), axis=0)

array([[6, 5, 8],
       [2, 6, 1],
       [9, 9, 6],
       [3, 3, 5]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[6, 5, 8, 9, 9, 6],
       [2, 6, 1, 3, 3, 5]])

In [ ]:

m= np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.split(m , [1,3], axis=0)

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [ ]:
twoD = np.random.randint(5,100,(3,3))
twoD

array([[85, 81, 15],
       [19,  7, 74],
       [91, 69, 71]])

In [ ]:
np.sort(twoD,axis=0)

array([[19,  7, 15],
       [85, 69, 71],
       [91, 81, 74]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Splitting of the Arrays</p>

<a id="000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``np.split(ary, indices_or_sections, axis=0)``**

In [ ]:
x= np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [ ]:
np.split(x,[3,5],axis=0)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [ ]:
len(np.slit)

AttributeError: ignored

If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[3, 5]`` would, for ``axis=0``, result in
- ``ary[:3]``
- ``ary[3:5]``
- ``ary[5:]``

The number of the elements ``should be divisible`` by 4, otherwise raises an error. If the argument (here is 4) is not enclosed by square brackets, then it means dividing into 4 pieces.

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Sorting of the Arrays</p>

<a id="0000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="0000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing & Selection</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this part of the lecture we will discuss how to select elements or groups of elements from an array.

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. [SOURCE](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp)

### ``Types of Indexing``

There are **``two types of indexing:``**

**``1 - Basic Slicing and indexing:``** Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :
- a slice object that is of the form start : stop : step
- an integer
- or a tuple of slice objects and integers

**``2 - Advanced indexing:``** Advanced indexing is triggered when obj is –

- an ndarray of type integer or Boolean
- or a tuple with at least one sequence object
- is a non tuple sequence object

For more information, please visit [INDEXING SOURCE](https://www.geeksforgeeks.org/numpy-indexing/)


[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://numpy.org/doc/stable/reference/arrays.indexing.html),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://pandas.pydata.org/pandas-docs/version/1.2.4/user_guide/indexing.html),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=9nbBTaz2qXI) &
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Bracket Indexing & Selection</p>

<a id="1.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

The simplest way to pick one or some elements of an array looks very similar to python lists:

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Indexing a 2D Array (Matrices)</p>

<a id="1.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row, col]</b>.<br> 
It's usually recommended using the comma notation for clarity.</p>

![image.png](https://i.ibb.co/pvdHbBm/numpy-index.png)

![image-2.png](https://i.ibb.co/jJPp6hk/numpy-indexing2.png)

[SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Fmedium.com%2F%40msjahid%2Fnumpy-array-indexing-slicing-23b70abb8433&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAk), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fiq.opengenus.org%2F2d-array-in-numpy%2F&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAp)<br>

In [ ]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

arr_2d

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Slicing a 2D Array (Matrices)</p>

<a id="1.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you know how to select subsets of Python lists, you know most of what you need to know about ndarray slicing. The elements of the array being indexed that correspond to the elements of the indexing object are returned in a new array. The most important aspect of indexing is to remember that there is more than one dimension, and the indexing method should be able to handle these other dimensions.

![image-2.png](https://i.ibb.co/64DGhj7/Numpy-index.jpg)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F16096753%2Fpython-array-slicing-how-can-2d-array-slicing-be-implemented&psig=AOvVaw0cHqeY-itYpRm19imsEBuR&ust=1644054927553000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCNiUt4vk5fUCFQAAAAAdAAAAABAD)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Fancy Indexing</p>

<a id="1.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once [SOURCE](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.). In Fancy Indexing, we pass array of indices instead of single scalar(numbers) to fetch elements at different index points. Remember that the shape of the output depends on the shape of the index arrays rather than the shape of the array being indexed. [SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftahamaddam.com%2Fcoding%2Fnumpy%2Fnumpy-fancy-indexing%2F&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAD), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F52485840%2Fnumpy-fancy-indexing-with-tuples%3Frq%3D1&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAO), [VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

Fancy indexing allows the following

<h3>any_array[[row indices], [column indices]]</h3>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Index*** & ***Fancy Index*** Together</p>

<a id="1.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>



### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Slicing*** & ***Fancy Index*** Together</p>

<a id="1.6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">More Indexing Help</p>

<a id="1.7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fscipy-lectures.org%2Fintro%2Fnumpy%2Farray_object.html&psig=AOvVaw21eb1iMrmWndUhejWXLkY-&ust=1644056657663000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCICAqr_q5fUCFQAAAAAdAAAAABAD)

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views. [SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Selection on a Condition</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's briefly go over how to use brackets for selection based off of comparison operators.

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Broadcasting</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy arrays differ from a normal Python list because of their ability to broadcast [SOURCE](https://numpy.org/doc/stable/user/theory.broadcasting.html).<br>

**``Broadcasting``** is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size [SOURCE](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20is%20the%20name%20given,a%20different%20shape%20or%20size.&text=Subject%20to%20certain%20constraints%2C%20the,that%20they%20have%20compatible%20shapes.).<br>

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is **``broadcast``** across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation [SOURCE](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).<br> 

Broadcasting is an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays (eg per-element aritmetic) [SOURCE01](https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73), [SOURCE02](https://towardsdatascience.com/a-numpy-affair-broadcasting-ead20d9661f).<br>

**NumPy Broadcasting Limitations**<br>
Broadcasting is a very easy and handy tool when working with Numpy arrays. Although, there are many rules and restrictions to perform the operations.

There are constraints on the dimension and shape of the arrays. We can perform broadcasting in cases where both the arrays have the same shape or only if either of the two has a size of 1. Also, we have to consider the dimensions in reverse order. We count it from the trailing dimension [SOURCE](https://data-flair.training/blogs/numpy-broadcasting/).<br>

Be informed about the discussion on [When broadcasting is a bad idea? (numpy)](https://stackoverflow.com/questions/47309818/when-broadcasting-is-a-bad-idea-numpy) at Stackoverflow.

More Sources: [SOURCE01](https://inblog.in/Broadcasting-in-Numpy-A-Complete-Guide-jfKy2vzHiY), [SOURCE02](https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations), [SOURCE03](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/), [SOURCE04](https://www.askpython.com/python-modules/numpy/numpy-broadcasting), [SOURCE05](https://stackoverflow.com/questions/32832923/numpy-what-is-broadcasting), [SOURCE06](https://stackoverflow.com/questions/61090539/how-can-i-use-broadcasting-with-numpy-to-speed-up-this-correlation-calculation), [SOURCE07](https://stackoverflow.com/questions/68185016/numpy-broadcasting-two-arrays-of-different-shape-to-matrix), [SOURCE08](https://stackoverflow.com/questions/50569344/broadcasting-using-numpys-sum-function)

Now **``note``** that the changes also occur in our original array!

Data is not copied, it's a view of the original array! This avoids memory problems!

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Operations</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

![image.png](https://i.ibb.co/n65mpTL/numpy-operations.png)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Statistical Calculations</p>

<a id="4.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Statistics is concerned with collecting and then analyzing that data. It includes methods for collecting the samples, describing the data, and then concluding that data. NumPy is the fundamental package for scientific calculations and hence goes hand-in-hand for NumPy statistical Functions.

NumPy contains various statistical functions that are used to perform statistical data analysis. These statistical functions are useful when finding a maximum or minimum of elements. It is also used to find basic statistical concepts like standard deviation, variance, etc.

NumPy is equipped with the following statistical functions:

**``np.amin(arr)``** This function determines the minimum value of the element along a specified axis.<br>
**``np.amax(arr)``** This function determines the maximum value of the element along a specified axis.<br>
**``arr.min()``** Returns minimum value of arr<br>
**``arr.max(axis=0)``** Returns maximum value of specific axis<br>
**``np.mean(arr, axis=0)``** It determines the mean value of the data set.<br>
**``np.median(arr)``** It determines the median value of the data set.<br>
**``np.std(arr, axis=1)``** It determines the standard deviation.<br>
**``np.var(arr)``** It determines the variance.<br>
**``np.ptp(arr)``** It returns a range of values (maximum - minimum) along an axis.<br>
**``np.average(arr)``** It determines the weighted average.<br>
**``np.percentile(arr)``** It determines the nth percentile of data along the specified axis.<br>
**``np.corrcoef(arr)``** Returns correlation coefficient of array

More Sources: [SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/), [SOURCE02](https://python-tricks.com/statistical-functions-in-numpy/), [SOURCE03](https://numpy.org/doc/stable/reference/routines.statistics.html), [SOURCE04](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), [SOURCE05](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), [SOURCE06](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), [SOURCE07](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE08](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE09](https://www.codecademy.com/learn/intro-statistics-numpy)

In [ ]:
numbers = range(11)
my_list = list(numbers)
my_list.sort(reverse=True)
print(my_list)



  
  
  



[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [ ]:
colors = ["red", ("blue", ["yellow", "green"]), "pink"]
print(colors[1])

('blue', ['yellow', 'green'])


In [ ]:
student_ages = {"Harry": 29,
                "Clark": 32,
                "Peter": 22,
                "Bruce": 36
                }

print(student_ages["Clark"])

32


In [ ]:
numbers_10 = [10, 30, 40, 50, 60, 70, 80, 90, 100]
numbers_10.insert(1,20)
print(numbers_10)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [ ]:
family_members = ['Meghan', 'Tom', 'Nicole', 'Tim']
print(tuple(family_members))

('Meghan', 'Tom', 'Nicole', 'Tim')


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
33//2

16

In [ ]:
pwd


In [ ]:
with open("rumi.txt","r", encoding="utf-8") as rumi :
  print(rumi.read(33))
  print(rumi.read(15))

  rumi.seek(0)

  print(rumi.read(33))
  print(rumi.tell())

I want to sing
Like the birds sin
g,
Not worrying
I want to sing
Like the birds sin
34


In [ ]:
with open("rumi.txt","r", encoding="utf-8") as rumi :

  print(rumi.readline())
  print(rumi.readline())
  print(rumi.readline(50))     #readline komutu sadece satirda islem yapar
                              #read yaparsan metnin tamaminda islem yaparsin

I want to sing

Like the birds sing,

Not worrying about



In [ ]:
ls


fishes.txt  rumi.txt  sample_data/


In [ ]:
import os


In [ ]:
os.listdir()

['.config', 'fishes.txt', 'rumi.txt', 'sample_data']

In [ ]:
import shutil

In [ ]:
shutil.make_archive("dosyalar_zip","zip","dosyalar1")

'/content/dosyalar_zip.zip'

In [ ]:
with open("fishes.txt" , "r" , encoding="utf-8") as file :
  fish = file.readlines()
  

In [ ]:
fish

['Orca is a kind of Dolphin.\n',
 'Blue Whale is the largest animal known on earth.\n',
 'Sharks are the sister group to the Rays (batoids).\n',
 'The Tuna Fish can weigh up to 260 kg.\n',
 'Squid and Octopus are in the same class.']

In [ ]:
type(fish)

list

In [ ]:
for line in fish:
  print(line)

Orca is a kind of Dolphin.

Blue Whale is the largest animal known on earth.

Sharks are the sister group to the Rays (batoids).

The Tuna Fish can weigh up to 260 kg.

Squid and Octopus are in the same class.


In [ ]:
money=1000
day_kar=(money*7)/100
new_money=money+day_kar
new_money

1070.0

In [ ]:
money=1000
day=0


for i in range(money) :
  i = i + (i*7/100)
  for a in range(day):
    a = a + 1
    while a == 7 :
      break
  

  print(i,"$")

In [38]:
money = "1000"
day = 1 
 
for day in range(1,8):
  money = float(money) + (float(money)*7/100)
  print("PARANIZ:", round(money,10) , "    "    "GUN:" ,(day))


 

   


  
  


PARANIZ: 1070.0     GUN: 1
PARANIZ: 1144.9     GUN: 2
PARANIZ: 1225.043     GUN: 3
PARANIZ: 1310.79601     GUN: 4
PARANIZ: 1402.5517307     GUN: 5
PARANIZ: 1500.730351849     GUN: 6
PARANIZ: 1605.7814764784     GUN: 7


In [47]:
age=input("Are you a cigarette addict older than 75 years old? (Please answer all questions with YES or NO)")
if age == "YES":
  age=False
chronic=input("Do you have a severe chronic disease?")
if chronic =="YES":
  chronic=False
immune=input("Is your immune system too weak?")
if immune =="YES":
  immune=False

if age and immune and chronic:
  print("Risk YOK")
else:
  print("Risk VAR")



Are you a cigarette addict older than 75 years old? (Please answer all questions with YES or NO)YES
Do you have a severe chronic disease?NO
Is your immune system too weak?NO
Risk VAR


In [51]:
derece=float(input("What is the temperature ? (Celcius)"))
fahr=(derece*9/5)+32
print(fahr)

#1km=0,6 mile yaklasik hesap kullandim

km=float(input("how many kilometers away? (km)"))
mile=km*6/10
print(mile)



What is the temperature ? (Celcius)55
131.0
how many kilometers away? (km)2
1.2


In [52]:
print(not 0 and "write me")

write me


In [64]:
sayi=(input("Write a number: "))
if (int(sayi) % 4 == 0) and (int(sayi) % 400 == 0):
  print("artik yil")
elif int(sayi) % 100 == 0:
  print("artik yil degil")
else:
  print("artik yil degil")

  





Write a number: 2400
artik yil


In [67]:
list_nbrs=[11,22,33,44,55,2,3,4,5,66,55,7,55,78,55,55,55,55]
tekrar=list_nbrs.pop()
print("en cok tekrar eden rakam:" ,tekrar)
tekrar_sayisi = list_nbrs.count(tekrar)
print("Tekrar sayisi: " ,tekrar_sayisi)


en cok tekrar eden rakam: 55
Tekrar sayisi:  6
